[project]
name = "java_type_narrowing"

[topo]
root = "topo/main.topo"

[build]
language = "java"
sources = ["src/main/java"]
output = "java_type_narrowing.jar"
output_type = "exe"

[build.java]
target_version = "21"

[optimize.type-narrowing]
mode = "force"

[builder]
mode = "dev"
