[project]
name = "java_loop_vectorize"

[topo]
root = "topo/main.topo"

[build]
language = "java"
sources = ["src/main/java"]
output = "java_loop_vectorize.jar"
output_type = "exe"

[build.java]
target_version = "21"

[parallel]
mode = "force"

[loop_parallel]
mode = "force"

[builder]
mode = "dev"
