[project]
name = "java_observability_base"

[topo]
root = "topo/main.topo"

[build]
language = "java"
sources = ["src/main/java"]
output = "java_observability_base.jar"
output_type = "exe"

[build.java]
target_version = "21"

[observability]
mode = "off"

[builder]
mode = "dev"
