[project]
name = "java_lifetime"

[topo]
root = "topo/main.topo"

[build]
language = "java"
sources = ["src/main/java"]
output = "java_lifetime.jar"
output_type = "exe"

[build.java]
target_version = "21"

[lifetime]
mode = "force"
default_arena_size = 65536

[builder]
mode = "dev"
